blank_issues_enabled: false
contact_links:
  - name: ‚ùì Questions / Feedback
    url: https://github.com/BlackyHawky/Clock/discussions/new/choose
    about: Post your questions or feedback in the discussions panel
